# Generated by Django 4.2.3 on 2023-07-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0003_device_mac_address_device_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='Company',
            new_name='company',
        ),
    ]
