# Generated by Django 4.2.3 on 2023-07-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0004_rename_company_device_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', related_query_name='device', to='Track.company'),
        ),
        migrations.AlterField(
            model_name='deviceallocation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_allocation', to='Track.employee'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='device_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_log', to='Track.deviceallocation'),
        ),
    ]
