# Generated by Django 4.2.3 on 2023-07-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0005_alter_device_company_alter_deviceallocation_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceallocation',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deviceallocation',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_allocation_device', to='Track.device'),
        ),
        migrations.AlterField(
            model_name='deviceallocation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_allocation_employee', to='Track.employee'),
        ),
    ]
