# Generated by Django 4.2.3 on 2023-07-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0006_deviceallocation_checked_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelog',
            name='condition',
        ),
    ]
