# Generated by Django 4.2.3 on 2023-07-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0007_remove_devicelog_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceallocation',
            name='checked_out',
        ),
    ]
